version: '3'
services:
  pergola-live-fdroid:
    restart: unless-stopped
    build:
      context: .
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.pergola-live-fdroid.loadbalancer.server.port=80"
      - "traefik.http.routers.pergola-live-fdroid.service=pergola-live-fdroid"
      - "traefik.http.routers.pergola-live-fdroid.rule=Host(`fdroid.pergola.gra.one`)"
      - "traefik.http.routers.pergola-live-fdroid.entrypoints=websecure"
      - "traefik.http.routers.pergola-live-fdroid.tls.certresolver=myresolver"
networks:
  traefik:
    external: true
